---
- name: Create group
  group: >
    name={{app_group}} gid={{app_gid}} state=present

- name: Create user
  user: >
    name={{app_user}} uid={{app_uid}} group={{app_group}} 
    home={{app_home}} createhome=yes password={{app_user_pwd}} shell=/bin/bash state=present

- name: Create folders
  file: >
    path={{item}} owner={{app_user}} group={{app_group}} 
    mode=1700 state=directory
  with_items:
    - "{{app_home}}"
    - "{{app_home}}/gems"
    - "{{app_repo}}"

- name: Clone application repository
  git: >
    repo={{app_repo_url}} dest={{app_repo}} 
    version=master accept_hostkey=yes force=yes
  sudo_user: "{{app_user}}"

- name: Copy dotEnv for this server
  copy: >
    src=.env dest={{app_repo}}/.env owner={{app_user}} group={{app_group}} mode=0600

- name: Symlink persistent folders
  file: state=link force=yes src={{item.src}} dest={{item.dest}}
  with_items:
    - { src: "{{app_home}}/gems", dest: "{{app_repo}}/vendor/bundle" }

- name: Bundle install in deployment mode
  shell: >
    bundle install --deployment --clean --without development test
  args:
    chdir: "{{app_repo}}"
  sudo_user: "{{app_user}}"

- name: mkdir -p ~{{app_repo}}/shared/config
  file: path=~{{app_repo}}/shared/config state=directory

- name: Copy database.yml to config
  sudo: yes
  template:
    src: "database.yml.j2"
    dest: "~{{app_repo}}/shared/config/database.yml"
    owner: "{{app_user}}"
    group: "{{app_group}}"
    mode: 0640

- name: Add apache vhosts configuration.
  template:
    src: "vhosts.conf.j2"
    dest: "{{ apache_conf_path }}/sites-available/vhosts.conf"
    owner: root
    group: root
    mode: 0644

- name: Add vhost symlink in sites-enabled.
  file:
    src: "{{ apache_conf_path }}/sites-available/vhosts.conf"
    dest: "{{ apache_conf_path }}/sites-enabled/vhosts.conf"
    state: link
  notify: restart apache

- name: Bundle install in deployment mode
  shell: >
    bundle exec rake db:setup
  args:
    chdir: "{{app_repo}}"
  sudo_user: "{{app_user}}"

- name: Create system service
  shell: >
    PATH=$(pwd):$PATH bundle exec foreman export -a {{app_name}} -u {{app_user}} upstart /etc/init/
  args:
    chdir: "{{app_repo}}"

- name: Restart service and enable at boot
  service: name={{app_name}} state=restarted enabled=yes
